### ISSUE TITLE
Unable to install Viewsb: "No matching distribution found for usb_protocol"

### ISSUE THREAD

**Issue by ma6254** [usb-tools/ViewSB#92] opened 2022-06-29 14:10 UTC
OS:

```bsh
➜  uname -a                      
Linux mjc-virtual-machine 5.13.0-41-generic #46~20.04.1-Ubuntu SMP Wed Apr 20 13:16:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
➜  
```

Operating procedures:

```bash
➜  python3 -V       
Python 3.8.10
➜  python3 -m pip -V
pip 22.1.2 from /home/mjc/.local/lib/python3.8/site-packages/pip (python 3.8)
➜  
```

```bash
➜  git clone https://github.com/greatscottgadgets/ViewSB.git
。。。
➜  python3 -m pip install . --proxy http://192.168.43.1:7890 
Defaulting to user installation because normal site-packages is not writeable
Processing /home/mjc/prog/luna_usb/ViewSB
  Preparing metadata (setup.py) ... done
Collecting construct
  Using cached construct-2.10.68.tar.gz (57 kB)
  Preparing metadata (setup.py) ... done
Collecting bitstruct
  Using cached bitstruct-8.15.1.tar.gz (34 kB)
  Preparing metadata (setup.py) ... done
Collecting tableprint
  Using cached tableprint-0.9.1-py3-none-any.whl (6.8 kB)
Collecting urwid
  Using cached urwid-2.1.2.tar.gz (634 kB)
  Preparing metadata (setup.py) ... done
ERROR: Could not find a version that satisfies the requirement usb_protocol (from viewsb) (from versions: none)
ERROR: No matching distribution found for usb_protocol
➜  
```

**Comment by smunaut** [comment] 2022-09-14 11:18
Not sure what the issue is but locally I did :

`pip install git+https://git@github.com/usb-tools/python-usb-protocol.git`

and that was good enough.

**Comment by mosquito520** [comment] 2024-05-26 16:01
> Not sure what the issue is but locally I did :
> 
> `pip install git+https://git@github.com/usb-tools/python-usb-protocol.git`
> 
> and that was good enough.

I've try this and failed
When I open the url https://git@github.com/usb-tools/python-usb-protocol.git
it has been redirect to https://github.com/greatscottgadgets/python-usb-protocol

so I've test command with new url 
pip install git+https://github.com/greatscottgadgets/python-usb-protocol
it would install a package with name UNKNOWN, and viewsb.sh fail to locate usb_protocol
so I've test pip install git+https://github.com/greatscottgadgets/python-usb-protocol@0.0.2
but it failed still.

so any suggest to make it work?

(Update the question description)

**Comment by antoinevg** [comment] 2024-05-28 17:19
We'll have official releases for `usb-protocol` in the next couple weeks, for now you can try:

```
pip install "usb-protocol @ git+https://github.com/greatscottgadgets/python-usb-protocol"
```

**Comment by mosquito520** [comment] 2024-05-29 09:38
> We'll have official releases for `usb-protocol` in the next couple weeks, for now you can try:
> 
> ```
> pip install "usb-protocol @ git+https://github.com/greatscottgadgets/python-usb-protocol"
> ```

Hi antoinevg

Thanks for the reply first
unfortunately it is still failed
I've post the install log with verbose args
is that missing setup.py?

Thanks!
 
<pre><font color="#8AE234"><b>mosquito@mosquito-X260</b></font>:<font color="#729FCF"><b>~/test</b></font>$ pip -v install &quot;usb-protocol @ git+https://github.com/greatscottgadgets/python-usb-protocol&quot;
Using pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)
Defaulting to user installation because normal site-packages is not writeable
Collecting usb-protocol@ git+https://github.com/greatscottgadgets/python-usb-protocol
  Cloning https://github.com/greatscottgadgets/python-usb-protocol to /tmp/pip-install-chbb3vhx/usb-protocol_f041860f504149f59cc5a695b8b02028
  Running command git version
  git version 2.34.1
  Running command git clone --filter=blob:none https://github.com/greatscottgadgets/python-usb-protocol /tmp/pip-install-chbb3vhx/usb-protocol_f041860f504149f59cc5a695b8b02028
  正複製到 &apos;/tmp/pip-install-chbb3vhx/usb-protocol_f041860f504149f59cc5a695b8b02028&apos;...
  Running command git rev-parse HEAD
  5730bc08c5641c7c11fa827d2418dfaf22598004
  Resolved https://github.com/greatscottgadgets/python-usb-protocol to commit 5730bc08c5641c7c11fa827d2418dfaf22598004
  Running command pip subprocess to install build dependencies
  Collecting setuptools&gt;=64
    Using cached setuptools-70.0.0-py3-none-any.whl (863 kB)
  Collecting setuptools-git-versioning&lt;2
    Using cached setuptools_git_versioning-1.13.6-py3-none-any.whl (10 kB)
  Collecting packaging
    Using cached packaging-24.0-py3-none-any.whl (53 kB)
  Collecting toml&gt;=0.10.2
    Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
  Installing collected packages: toml, setuptools, packaging, setuptools-git-versioning
  Successfully installed packaging-24.0 setuptools-70.0.0 setuptools-git-versioning-1.13.6 toml-0.10.2
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  running egg_info
  creating UNKNOWN.egg-info
  writing manifest file &apos;UNKNOWN.egg-info/SOURCES.txt&apos;
  writing manifest file &apos;UNKNOWN.egg-info/SOURCES.txt&apos;
  Getting requirements to build wheel ... done
  Running command pip subprocess to install backend dependencies
  Collecting wheel
    Using cached wheel-0.43.0-py3-none-any.whl (65 kB)
  Installing collected packages: wheel
  Successfully installed wheel-0.43.0
  Installing backend dependencies ... done
  Running command Preparing metadata (pyproject.toml)
  running dist_info
  creating /tmp/pip-modern-metadata-cvgyz9_3/UNKNOWN.egg-info
  writing manifest file &apos;/tmp/pip-modern-metadata-cvgyz9_3/UNKNOWN.egg-info/SOURCES.txt&apos;
  writing manifest file &apos;/tmp/pip-modern-metadata-cvgyz9_3/UNKNOWN.egg-info/SOURCES.txt&apos;
  Preparing metadata (pyproject.toml) ... done
<font color="#C4A000">  WARNING: Generating metadata for package usb-protocol produced metadata for project name unknown. Fix your #egg=usb-protocol fragments.</font>
Discarding <font color="#3465A4"><u style="text-decoration-style:single">git+https://github.com/greatscottgadgets/python-usb-protocol</u></font>: <font color="#C4A000">Requested unknown from git+https://github.com/greatscottgadgets/python-usb-protocol has inconsistent name: filename has &apos;usb-protocol&apos;, but metadata has &apos;unknown&apos;</font>
<font color="#CC0000">ERROR: Could not find a version that satisfies the requirement usb-protocol (unavailable) (from versions: 0.0.1, 0.0.2)</font>
<font color="#CC0000">ERROR: No matching distribution found for usb-protocol (unavailable)</font>
<font color="#8AE234"><b>mosquito@mosquito-X260</b></font>:<font color="#729FCF"><b>~/test</b></font>$ 
</pre>

**Comment by antoinevg** [comment] 2024-05-29 10:59
Ah, the issue here may be that your `pip` version is `22` and there's been quite a lot of churn with python packaging over the last two years. Are you able to update your `pip` to version 24 ?

**Comment by mosquito520** [comment] 2024-05-29 11:21
> Ah, the issue here may be that your `pip` version is `22` and there's been quite a lot of churn with python packaging over the last two years. Are you able to update your `pip` to version 24 ?

Ah~~ it's worked !!!! 
I've install usb-protocol sucessfully!
Now I can study how to using ViewSB now

Thanks for your help :D

**Comment by martinling** [comment] 2024-08-01 15:47
Closed in preparation for archiving the repository. We have replaced ViewSB with [Packetry](https://github.com/greatscottgadgets/packetry).

**Closed as not planned by martinling** 2024-08-01 15:47 UTC
Labels: technical support
