### ISSUE TITLE
Grouping "hides" packets until the group is complete

### ISSUE THREAD

**Issue by smunaut** [usb-tools/ViewSB#14] opened 2019-07-19 20:02 UTC
What happens is that packets are only shown on the UI when the "group" logic flushes and think the group is done. That logic is fine if you're viewing a file or a capture that's ended, but when doing live capture, this presents a view that's far from reality.

Especially when debugging issues where transactions are invalid / incomplete, a lot of packet just end up in limbo and never shown.

I think ideally any packet that has been received should be shown in the UI, and so "incomplete" groups should already be there and progressively filled / updated. That's unfortunately not trivial :/

**Comment by ktemkin** [comment] 2019-07-19 21:49
Yep -- the whole analyzer stack is currently missing periodic "tick" that allows things to e.g. time out while being aggregated.

It also might be nice to have a feature that allows us to gather up "in progress" packets and display them somewhere in the UI -- though most timeouts should prevent them from sticking anywhere for any appreciable amount of time.

**Comment by xairy** [comment] 2020-03-30 22:05
Possibly caused by the same issue as suggested on Discord:

> I'm trying to use ViewSB to sniff USB mouse communication with `openvizsla` backend (`./viewsb.sh openvizsla --speed=low`), but I'm only seeing control requests, not the interrupt ones. At the same time I'm seeing all requests properly when using the original OpenVizsla software (`./software/host/ovctl.py sniff ls`), and when using the `usbmon` backend of ViewSB (`./viewsb.sh usbmon --file=/dev/usbmon1`).

**Comment by mndza** [comment] 2024-08-01 15:48
Closed in preparation for archiving the repository. We have replaced ViewSB with [Packetry](https://github.com/greatscottgadgets/packetry).

**Closed as not planned by mndza** 2024-08-01 15:48 UTC
Labels: bug, enhancement
